apps/funcionarios/urls.py
from django.urls import path
from .views import \
    FuncionariosList, \
    FuncionarioEdit, \
    FuncionarioNovo, \
    FuncionarioDelete


urlpatterns = [
    path('cadastro/list/', FuncionariosList.as_view(), name='list_funcionario'),
    path('cadastro/new/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('cadastro/delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('cadastro/update/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('', include('apps.core.urls')),
    path('registro_horas_extras/', include('apps.registro_horas_extras.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += [
      url(r'^media/(?P<path>.*)$',
          serve, {'document_root':
                  settings.MEDIA_ROOT, }), ]

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.db import models
from django.utils.timezone import now
from django.db.models import Sum, Avg, Count


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    funcao = models.CharField(max_length=100, verbose_name='Função')
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='img/perfil', verbose_name='Foto de perfil') #'img_perfil/%Y/%m/%D/'
    data_created = models.DateTimeField(editable=True, null=True, blank=True, default=now, verbose_name='Data cadastro')

    def get_absolute_url(self):
        return reverse('list_funcionario')

    @property
    def total_horas_extras(self):
        totalhe = self.registrohoraextra_set.all().aggregate(
            Sum('time_he1'))['time_he1__sum']
        return totalhe

    @property
    def media_horas_extras(self):
        totalhe = self.registrohoraextra_set.all().aggregate(
            Avg('time_he1'))['time_he1__avg']
        return totalhe

    @property
    def qtd_horas_extras(self):
        totalhe = self.registrohoraextra_set.all().aggregate(
            Count('time_he1'))['time_he1__count']
        return totalhe

    def __str__(self):
        return self.nome + " " + self.sobrenome

apps/registro_horas_extras/models.py
from django.db import models
from django.urls import reverse
from apps.funcionarios.models import Funcionario
from django.utils.timezone import now
from django.db.models import Sum, Avg, Count


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100, verbose_name='Motivo da Hora Extra')
    observacao = models.TextField(max_length=500, verbose_name='Observação')
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    date_time_he = models.DateTimeField(
            editable=True,
            null=True,
            blank=True,
            default=now,
            verbose_name='Data e Hora Inicial')
    time_he1 = models.DurationField(blank=True, null=True, verbose_name='Tempo total')

    def time_he1_duration_HHmm(self):
        sec = self.time_he1.total_seconds()
        return '%02d:%02d' % (int((sec / 3600) % 3600), int((sec / 60) % 60))

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

apps/funcionarios/forms.py
from django.forms import ModelForm
from apps.funcionarios.models import Funcionario


class DepartamentoForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(DepartamentoForm, self).__init__(*args, **kwargs)
        self.fields['departamentos'].queryset = Funcionario.objects.filter(
            empresa=user.funcionario.empresa
        )

    class Meta:
        model = Funcionario
        fields = [
            'nome',
            'departamentos',
        ]

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.template.defaultfilters import lower
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from apps.funcionarios.forms import DepartamentoForm
from .models import Funcionario


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'sobrenome', 'funcao', 'departamentos', 'image', 'data_created']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionario')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'sobrenome', 'funcao', 'departamentos', 'image', 'data_created']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.sobrenome.split(' ')[0]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=lower(username))
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'starter.html' %}
{% load static %}
{% load bootstrap %}
<!--
   Use as tags para invalidar parte dos códigos ou o block
   -->
{% block title %}
ExpNEP | Funcionários
{% endblock %}
{% block header %}
<section class="content-header">
   <h1>
      Gerenciar Funcionários
      <small>
      </small>
   </h1>
   <ol class="breadcrumb">
      <a href="{% url 'list_funcionario' %}" class="btn btn-sm btn-primary">Voltar</a>
   </ol>
</section>
{% endblock %}
{% block main %}
<section class="content">
   <div class="row">
      <!-- Menssagem -->
      <div class="col-md-12">
         <div class="box box-default">
            <div class="box-header with-border">
               <i class="fa fa-bullhorn"></i>
               <h3 class="box-title">Atenção, tem certeza que deseja excluir o registro?</h3>
               <div class="box-tools pull-right">
                  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
               </div>
               <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               <form method="POST">
                  <div class="col-md-12">
                     <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                           <div class="info-box bg-yellow">
                              <span class="info-box-icon">
                                 <i class="fa fa-fw fa-user-times"></i>
                              </span>
                              <div class="info-box-content">
                                 <span class="info-box-text">{{ object }}</span>
                                 <span class="info-box-number">{{ object.funcao }}</span>
                                 <span class="progress-description">
                                 {{ object.user }}
                                 </span>
                              </div>
                              <!-- /.info-box-content -->
                           </div>
                           <!-- /.info-box -->
                        </div>


                     </div>
                     {% csrf_token %}
                     {{ form }}
                  </div>
                  <br>
                  <br>
                  <div class="col-md-12">
                     <button type="submit" class="btn btn-danger">
                        <i class="fa fa-fw fa-trash-o"></i>
                         Confirmar
                     </button>
                  </div>
               </form>
            </div>
         </div>
         <!-- /.box-body -->
      </div>
      <!-- /.box -->
   </div>
</section>
{% endblock %}
{% block search_sidebar %}
{% endblock %}
{% block logo_sidebar %}
{% include 'block_logo_sidebar.html' %}
{% endblock %}
{% block topside_menu_messages %}
{% include 'block_topside_menu_messages.html' %}
{% endblock %}
{% block topside_menu_tasks %}
{% include 'block_topside_menu_tasks.html' %}
{% endblock %}
{% block topside_menu_notifications %}
{% include 'block_topside_menu_notifications.html' %}
{% endblock %}
{% block topside_useraccount_menu %}
{% include 'block_topside_useraccount_menu.html' %}
{% endblock %}
{% block userpanel_sidebar %}
{% include 'block_userpanel_sidebar.html' %}
{% endblock %}
{% block right_sidebar_custon %}
{% include 'block_right_sidebar_custon.html' %}
{% endblock %}
{% block menu_sidebar %}
{% include 'block_menu_sidebar.html' %}
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'starter.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}
ExpNEP | Funcionários
{% endblock %}
{% block header %}
<section class="content-header">
   <h1>
      Gerenciar Funcionários
      <small>
      </small>
   </h1>
</section>
{% endblock %}
{% block main %}
<section class="content">
   <div class="row">
      <!-- Form Cadastro -->
      <form method="POST" role="form" enctype="multipart/form-data" autocomplete="off">
         {% csrf_token %}
         <div class="col-md-12">
            <div class="box box-default">
               <div class="box-header with-border">
                  <i class="fa fa-user"></i>
                  <h3 class="box-title">
                     {% if object %}
                     Editar funcionário
                     {% endif %}
                     {% if not object %}
                     Novo funcionário
                     {% endif %}
                  </h3>
                  <div class="box-tools pull-right">
                     <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                     </button>
                  </div>
                  <!-- /.box-tools -->
               </div>
               <div class="box-body">
                  <div class="row">
                     <div class="col-md-6">
                        {{ form.nome|bootstrap }}
                     </div>
                     <div class="col-md-6">
                        {{ form.sobrenome|bootstrap }}
                     </div>
                     <div class="col-md-12">
                        {{ form.funcao|bootstrap }}
                     </div>
                     <div class="col-md-12">
                        {{ form.departamentos|bootstrap }}
                     </div>
                     {% if object.image %}
                     <div class="col-md-2">
                        <img src="{{ funcionario.image.url }}" class="img-rounded" width="168" height="168">
                     </div>
                     {% endif %}
                     {% if not object.image %}
                     <div class="col-md-2">
                        <img src="{% static 'AdminLTE/dist/img/default-50x50.gif' %}" class="img-rounded" width="128" height="128">
                     </div>
                     {% endif %}
                     <div class="col-md-6">
                        {{ form.image|bootstrap }}
                     </div>
                     <div class="col-md-6">
                        {{ form.data_created|bootstrap }}
                     </div>
                  </div>
                  <!-- /.box-body -->
                  <div class="box-footer">
                     <div class="row">
                        <div class="col-md-4">
                           {% if object %}
                           <a href="{% url 'delete_funcionario' funcionario.id %}" title="Deletar" class="btn btn-flat btn-danger">
                           <i class="fa fa-fw fa-trash-o"></i>
                           </a>
                           {% endif %}
                        </div>
                        <div class="col-md-8">
                           <div class="pull-right">
                              {% if object %}
                              <a href="{% url 'create_hora_extra_extends' object.id %}" title="Adicionar HE" class="btn btn-default btn-flat">
                              <i class="fa fa-fw fa-hourglass-o"></i>
                              </a>
                              <a href="{% url 'create_documento_func' object.id %}" title="Adicionar documento" class="btn btn-primary btn-flat">
                              <i class="fa fa-fw fa-paperclip"></i>
                              </a>
                              {% endif %}
                              <a href="{% url 'list_funcionario' %}" title="Voltar" class="btn btn-flat btn-info">
                              <i class="fa fa-fw fa-undo"></i>
                              </a>
                              <button type="submit" title="Salvar" class="btn btn-flat btn-success">
                              <i class="fa fa-fw fa-save"></i>
                              </button>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </form>
         {% if object.documento_set.all %}
         <div class="col-md-12">
            <div class="box box-primary">
               <div class="box-header with-border">
                  <i class="fa fa-sticky-note"></i>
                  <h3 class="box-title">
                     Documentos
                  </h3>
               </div>
               <!-- /.box-header -->
               <br>
               <!-- /.if -->
               <div class="container-fluid">
                  <div class="row display:felx;">
                     {% for documento in object.documento_set.all %}
                     <div class="col-lg-2 col-xs-3" align="center">
                        <a href="{% url 'update_documento' documento.id %}">
                        <img src="{{ documento.arquivo.url }}" title="{{ documento.descricao }}" class="img-rounded" width="78" height="78">
                        </a>
                        <p class="text-center users-list-name">
                           <strong>
                           {{ documento.descricao }}
                           </strong>
                        </p>
                     </div>
                     {% endfor %}
                     <!-- ./col -->
                  </div>
               </div>
               <!-- /.box-body -->
               <div class="box-footer text-center">
                  <p>...</p>
               </div>
               <!-- /.box-footer -->
            </div>
         </div>
         {% endif %}
         <!-- Menssagem -->
         {% if not object.documento_set.all %}
         <div class="col-md-12">
            <div class="box box-default">
               <div class="box-header with-border">
                  <i class="fa fa-bullhorn"></i>
                  <h3 class="box-title">Atenção</h3>
                  <div class="box-tools pull-right">
                     <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                     </button>
                  </div>
                  <!-- /.box-tools -->
               </div>
               <!-- /.box-header -->
               <div class="box-body">
                  <div class="callout callout-default">
                     <h4>Lista de documentos!</h4>
                     <p>Não existem registros no banco de dados.</p>
                  </div>
               </div>
            </div>
            <!-- /.box-body -->
         </div>
         {% endif %}

      {% if object.registrohoraextra_set.all %}
      <div class="col-md-4">
         <div class="info-box bg-aqua">
           <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
            <div class="info-box-content">
              <span class="info-box-text">Total Horas Extras</span>
              <span class="info-box-number">{{ object.total_horas_extras }}</span>
               <div class="progress">
                <div class="progress-bar" style="width: 100%"></div>
              </div>
            </div>
         </div>
      </div>
      <div class="col-md-4">
         <div class="info-box bg-aqua">
           <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
            <div class="info-box-content">
              <span class="info-box-text">Média Horas Extras</span>
              <span class="info-box-number">{{ object.media_horas_extras }}</span>
               <div class="progress">
                <div class="progress-bar" style="width: 100%"></div>
              </div>
            </div>
         </div>
      </div>
      <div class="col-md-4">
         <div class="info-box bg-aqua">
           <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
            <div class="info-box-content">
              <span class="info-box-text">Registro Horas Extras</span>
              <span class="info-box-number">{{ object.qtd_horas_extras }}</span>
               <div class="progress">
                <div class="progress-bar" style="width: 100%"></div>
              </div>
            </div>
         </div>
      </div>
         <div class="col-md-12">
            <div class="box box-default">
               <div class="box-header with-border">
                  <i class="fa fa-clock-o"></i>
                  <h3 class="box-title">
                     Horas Extras
                  </h3>
               </div>
               <!-- /.box-header -->
               <br>
               <!-- /.if -->

                     <div class="table-responsive">
                        <table class="table table-hover table-sm">
                           <thead class="bg-secondary text-white">
                              <tr style="background-color:rgba(0, 0, 0, 0.1);">
                                 <th scope="col">#</th>
                                 <th scope="col">Motivo</th>
                                 <th scope="col">Data</th>
                                 <th scope="col">Duração</th>
                                 <th scope="col">Progress</th>
                                 <th>Edit</th>
                              </tr>
                           </thead>
                           <tbody id="myList">
                              {% for registrohoraextra in object.registrohoraextra_set.all %}
                              <tr>
                                 <td scope="row">{{ registrohoraextra.id }}</td>
                                 <td scope="row">{{ registrohoraextra.motivo }}</td>
                                 <td scope="row">{{ registrohoraextra.date_time_he|date:'d/m/Y H:i' }}</td>
                                 <td scope="row">{{ registrohoraextra.time_he1_duration_HHmm }}</td>
                                  <td width="300" scope="row">
                                      <div class="progress progress active">
                                         <div class="progress-bar progress-bar-info progress-bar-striped"
                                             title="{{ registrohoraextra.time_he1_duration_HHmm }}"
                                             role="progressbar"
                                             aria-valuenow="20"
                                             aria-valuemin="0"
                                             aria-valuemax="100"
                                             style="width: 30%">
                                        </div>
                                        </div>
                                  </td>
                                 <td scope="row">
                                    <a href="{% url 'update_hora_extra' registrohoraextra.id %}">
                                       <button type="" class="btn btn-flat btn-xs btn-info">
                                          <i class="fa fa-pencil"></i>
                                       </button>
                                    </a>
                                    <a href="{% url 'delete_hora_extra' registrohoraextra.id %}">
                                       <button type="" class="btn btn-flat btn-xs btn-danger">
                                          <i class="fa fa-fw fa-trash-o"></i>
                                       </button>
                                    </a>
                                 </td>
                              </tr>
                              {% endfor %}
                           </tbody>
                        </table>
                     </div>

                     <!-- ./col -->


               <!-- /.box-body -->
               <div class="box-footer text-center">
                  <p>...</p>
               </div>
               <!-- /.box-footer -->
            </div>
         </div>
         {% endif %}
         <!-- Menssagem -->
         {% if not object.registrohoraextra_set.all %}
         <div class="col-md-12">
            <div class="box box-danger">
               <div class="box-header with-border">
                  <i class="fa fa-bullhorn"></i>
                  <h3 class="box-title">Atenção</h3>
                  <div class="box-tools pull-right">
                     <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                     </button>
                  </div>
                  <!-- /.box-tools -->
               </div>
               <!-- /.box-header -->
               <div class="box-body">
                  <div class="callout callout-default">
                     <h4>Lista de horas extras!</h4>
                     <p>Não existem registros no banco de dados.</p>
                  </div>
               </div>
            </div>
            <!-- /.box-body -->
         </div>
         {% endif %}


   </div>
</section>
{% endblock %}
{% block search_sidebar %}
{% endblock %}
{% block logo_sidebar %}
{% include 'block_logo_sidebar.html' %}
{% endblock %}
{% block topside_menu_messages %}
{% include 'block_topside_menu_messages.html' %}
{% endblock %}
{% block topside_menu_tasks %}
{% include 'block_topside_menu_tasks.html' %}
{% endblock %}
{% block topside_menu_notifications %}
{% include 'block_topside_menu_notifications.html' %}
{% endblock %}
{% block topside_useraccount_menu %}
{% include 'block_topside_useraccount_menu.html' %}
{% endblock %}
{% block userpanel_sidebar %}
{% include 'block_userpanel_sidebar.html' %}
{% endblock %}
{% block right_sidebar_custon %}
{% include 'block_right_sidebar_custon.html' %}
{% endblock %}
{% block menu_sidebar %}
{% include 'block_menu_sidebar.html' %}
{% endblock %}